version: '3.8'
services:
  postgres:
    image: postgres:15.1
    container_name: project_ignat
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 1s
      timeout: 1s
      retries: 30
    extra_hosts:
      - "host.docker.internal:host-gateway"
  flask:
    container_name: project
    build: .
    env_file: .env
    ports:
      - ${FLASK_PORT}:5000
    depends_on:
      postgres:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"
  flyway:
    image: flyway/flyway:9.8.1
    volumes:
      - ./migrations:/flyway/sql
    network_mode: host
    command: -url=jdbc:postgresql://127.0.0.1:${POSTGRES_PORT}/${POSTGRES_DB} -user=${POSTGRES_USER} -password=${POSTGRES_PASSWORD} migrate
    depends_on:
      postgres:
        condition: service_healthy
